# Lecture de notre dataset (csv)
input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/.movies_sincedb"
  }
}

# Filtrage et transformation des données
filter {
  csv {
    separator => ","
    quote_char => '"'
    skip_header => true
    columns => [
      "id", "title", "genres", "original_language", "overview",
      "popularity", "production_companies", "release_date", "budget",
      "revenue", "runtime", "status", "tagline", "vote_average",
      "vote_count", "credits", "keywords", "poster_path",
      "backdrop_path", "recommendations"
    ]
  }

 
  clone {
    clones => ["raw"]
  }

  # Nettoyage et transformation pour l'index "movies_clean"
  if [type] != "raw" {

    # Conversion de types
    mutate {
      convert => {
        "id"           => "integer"
        "popularity"   => "float"
        "budget"       => "integer"
        "revenue"      => "integer"
        "runtime"      => "float"
        "vote_average" => "float"
        "vote_count"   => "integer"
      }
    }

   # Conversion de la date au format(timestamp)
    date {
      match          => ["release_date", "yyyy-MM-dd"]
      target         => "release_date"
      tag_on_failure => ["_date_parse_failure"]
    }

    # On normalise notre liste  par des séparateurs(-)
    mutate {
      split => {
        "genres"   => "-"
        "keywords" => "-"
      }
    }

    # Détection des titres manquants (pour la mesure d'impact)
    if ![title] or [title] == "" {
      mutate { add_tag => ["missing_title"] }
    }

    # Nettoyage des champs techniques ajoutés par Logstash
    mutate {
      remove_field => ["@version", "host", "path", "message", "event"]
    }
  }
}

# En sortie, on aura nos deux index : "movies_raw" et "movies_clean"
output {
  if [type] == "raw" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "movies_raw"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "movies_clean"
    }
  }
}