input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  # C'est ici que tu feras le nettoyage plus tard (F3)
  csv {
    separator => ","
    autodetect_column_names => true
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_raw"
  }
  stdout { codec => rubydebug } # Pour voir ce qui se passe dans les logs
}