input {
  file {
    # Chemin vers le fichier dans le conteneur (défini dans ton docker-compose)
    path => "/data/movies.csv"
    start_position => "beginning"
    # Utilisation d'un chemin persistant pour éviter les doublons au redémarrage
    sincedb_path => "/usr/share/logstash/data/.movies_sincedb"
  }
}

filter {
  csv {
    separator => ","
    quote_char => '"'
    skip_header => true
    # Liste des colonnes basée sur ton image (ordre important !)
    columns => [
      "id", "title", "genres", "original_language", "overview", 
      "popularity", "production_companies", "release_date", "budget", 
      "revenue", "runtime", "status", "tagline", "vote_average", 
      "vote_count", "credits", "keywords", "poster_path", 
      "backdrop_path", "recommendations"
    ]
  }

  mutate {
    # Nettoyage : On convertit les textes en nombres pour Kibana
    convert => {
      "id" => "integer"
      "popularity" => "float"
      "budget" => "float"
      "revenue" => "float"
      "runtime" => "float"
      "vote_average" => "float"
      "vote_count" => "integer"
    }
  }

  date {
    # Format YYYY-MM-DD identifié sur ta capture
    match => ["release_date", "yyyy-MM-dd"]
    target => "release_date_ts"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "tmdb-movies-clean"
  }

  # Garde le stdout activé seulement pour le premier test
  # Si VS Code se ferme tout seul, supprime les 3 lignes ci-dessous
  stdout { 
    codec => rubydebug 
  }
}